# APP CONFIGURATION
spring.application.name=neuralforge_api

# SERVLET CONFIGURATION
server.servlet.context-path=/api/neuralforge/v1

# DATASOURCE CONFIGURATION
spring.datasource.url=${DB_DATASOURCE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JWT CONFIGURATION
security.jwt.secret-key=${JWT_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION}

# SENDGRID CONFIGURATION
spring.sendgrid.api-key=${SENDGRIND_API}
spring.sendgrid.sender-identity=${SENDGRIND_IDENTITY}

# GOOGLE OAUTH CONFIGURATION
oauth2.google.client-id=${OAUTH2_CLIENT_ID}
oauth2.google.client-secret=${OAUTH2_CLIENT_SECRET}

# DEEPSEEK API CONFIGURATION
deepseek.api.bearer-token=${DEEPSEEK_API_BEARER_TOKEN}

# CloudDinary API CONFIGURATION
# cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
# cloudinary.api_key=${CLOUDINARY_API_KEY}
# cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

# Upload directory
app.upload.dir=${user.home}/uploads
